models:
  - name: dim_movies
    description: Dimension table for cleansed movie metadata
    columns:
      - name: movie_id
        description: Primary key of the movie
        tests:
          - not_null
      - name: movie_title
        description: Standardized movie_title
        tests:
          - not_null
      - name: genre_array
        description: List of genres in array format
      - name: genres
        description: Raw genre string from sources


  - name: dim_users
    description: Dimension table of unique users from both ratings and tables
    columns:
      - name: user_id
        description: Unique user identifier
        tests:
          - not_null
          - unique


  - name: dim_genome_tags
    description: Dimension table of genome tag labels
    columns:
      - name: tag_id
        description: Unique tag ID
        test:
          - not_null
          - unique
      - name: tag_name
        description: Cleaned, human-readable tag name
        tests:
          - not_null